CREATE OR REPLACE FUNCTION public.update_updated_at_column() RETURNS TRIGGER LANGUAGE plpgsql SET search_path = public AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END; $$;
CREATE TABLE public.builder_pages (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), owner_id UUID NOT NULL, name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published')), theme JSONB NOT NULL DEFAULT '{}'::jsonb, seo JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE public.builder_blocks (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), page_id UUID NOT NULL REFERENCES public.builder_pages(id) ON DELETE CASCADE, type TEXT NOT NULL, data JSONB NOT NULL DEFAULT '{}'::jsonb, position INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX idx_builder_blocks_page ON public.builder_blocks(page_id, position);
CREATE INDEX idx_builder_pages_status ON public.builder_pages(status);
ALTER TABLE public.builder_pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.builder_blocks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "bp_pub_sel" ON public.builder_pages FOR SELECT USING (status = 'published');
CREATE POLICY "bp_own_sel" ON public.builder_pages FOR SELECT USING (auth.uid() = owner_id);
CREATE POLICY "bp_adm_all" ON public.builder_pages FOR ALL USING (public.has_role(auth.uid(), 'admin'::public.app_role)) WITH CHECK (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "bp_own_ins" ON public.builder_pages FOR INSERT WITH CHECK (auth.uid() = owner_id);
CREATE POLICY "bp_own_upd" ON public.builder_pages FOR UPDATE USING (auth.uid() = owner_id);
CREATE POLICY "bp_own_del" ON public.builder_pages FOR DELETE USING (auth.uid() = owner_id);
CREATE POLICY "bb_pub_sel" ON public.builder_blocks FOR SELECT USING (EXISTS (SELECT 1 FROM public.builder_pages p WHERE p.id = page_id AND p.status = 'published'));
CREATE POLICY "bb_own_sel" ON public.builder_blocks FOR SELECT USING (EXISTS (SELECT 1 FROM public.builder_pages p WHERE p.id = page_id AND p.owner_id = auth.uid()));
CREATE POLICY "bb_adm_all" ON public.builder_blocks FOR ALL USING (public.has_role(auth.uid(), 'admin'::public.app_role)) WITH CHECK (public.has_role(auth.uid(), 'admin'::public.app_role));
CREATE POLICY "bb_own_all" ON public.builder_blocks FOR ALL USING (EXISTS (SELECT 1 FROM public.builder_pages p WHERE p.id = page_id AND p.owner_id = auth.uid())) WITH CHECK (EXISTS (SELECT 1 FROM public.builder_pages p WHERE p.id = page_id AND p.owner_id = auth.uid()));
CREATE TRIGGER trg_builder_pages_updated BEFORE UPDATE ON public.builder_pages FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER trg_builder_blocks_updated BEFORE UPDATE ON public.builder_blocks FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();